# Generated by Django 4.1.13 on 2023-11-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_subdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='subdomain',
        ),
    ]
