# Generated by Django 4.1.13 on 2023-11-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_tenant_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(default='default_subdomain', max_length=100, unique=True),
        ),
    ]
