# Generated by Django 4.1.13 on 2023-11-19 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenantawaremodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.tenantawaremodel')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('tenants.tenantawaremodel',),
        ),
    ]
